//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Particle.Setup {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SetupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetupResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Particle.Setup.SetupResources", typeof(SetupResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials are invalid.
        /// </summary>
        public static string AuthCredentialsError {
            get {
                return ResourceManager.GetString("AuthCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists.
        /// </summary>
        public static string CreateCredentialsError {
            get {
                return ResourceManager.GetString("CreateCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required.
        /// </summary>
        public static string ErrorEmailIsRequired {
            get {
                return ResourceManager.GetString("ErrorEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        public static string ErrorPasswordIsRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password fields must match.
        /// </summary>
        public static string ErrorPasswordsMustMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token field is required.
        /// </summary>
        public static string ErrorTokenIsRequired {
            get {
                return ResourceManager.GetString("ErrorTokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a user with the supplied email address.
        /// </summary>
        public static string ForgotPasswordError {
            get {
                return ResourceManager.GetString("ForgotPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and follow the directions contained inside.
        /// </summary>
        public static string ForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured with {0}.
        /// </summary>
        public static string SecuredWith {
            get {
                return ResourceManager.GetString("SecuredWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh!.
        /// </summary>
        public static string SoftAPCompletedHeaderFailureConfigure {
            get {
                return ResourceManager.GetString("SoftAPCompletedHeaderFailureConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup completed successfully.
        /// </summary>
        public static string SoftAPCompletedHeaderSuccess {
            get {
                return ResourceManager.GetString("SoftAPCompletedHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup completed.
        /// </summary>
        public static string SoftAPCompletedHeaderSuccessDeviceOffline {
            get {
                return ResourceManager.GetString("SoftAPCompletedHeaderSuccessDeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup completed.
        /// </summary>
        public static string SoftAPCompletedHeaderSuccessUnknown {
            get {
                return ResourceManager.GetString("SoftAPCompletedHeaderSuccessUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup process couldn&apos;t configure the Wi-Fi credentials for your {device}, please try running setup again after resetting your {device} and putting it back in blinking blue listen mode if needed..
        /// </summary>
        public static string SoftAPCompletedTextFailureConfigure {
            get {
                return ResourceManager.GetString("SoftAPCompletedTextFailureConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats! You&apos;ve successfully set up your {device}..
        /// </summary>
        public static string SoftAPCompletedTextSuccess {
            get {
                return ResourceManager.GetString("SoftAPCompletedTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has been successfully claimed to your account, however it is offline. If the device was already claimed before this setup, then the Wi-Fi connection may have failed, and you should try setup again..
        /// </summary>
        public static string SoftAPCompletedTextSuccessDeviceOffline {
            get {
                return ResourceManager.GetString("SoftAPCompletedTextSuccessDeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup was successful, but since you do not own this device we cannot know if the {device} has connected to the Internet. If you see the LED breathing cyan this means it worked! If not, please restart the setup process..
        /// </summary>
        public static string SoftAPCompletedTextSuccessUnknown {
            get {
                return ResourceManager.GetString("SoftAPCompletedTextSuccessUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire time is in the past.
        /// </summary>
        public static string TokenCreateExpireTimePast {
            get {
                return ResourceManager.GetString("TokenCreateExpireTimePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire time is too soon.
        /// </summary>
        public static string TokenCreateExpireTimeSoon {
            get {
                return ResourceManager.GetString("TokenCreateExpireTimeSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
